### ISSUE TITLE
Package in AUR can not work

### ISSUE THREAD

**Issue by debeetle** [jpe90/clp#14]
Love this project. The package downloaded from AUR is not working, and the error information is 'failed to load clp.lua'. So I change the clprc.lua filename to clp.lua. But it came to be another error. I finally make from code and it works

**Comment by jpe90** [comment]
Thanks for your interest in my project and sorry for the trouble!

I tried reinstalling the AUR package on my system but I couldn’t reproduce the issue. Which OS/architecture are you using?

I’ll push a commit that adds extra debug information to try to find the issue if it happens in the future.

**Comment by debeetle** [comment]
Happy to hear from you! I am using arch linux. And uname -a output is '6.2.2-zen1-1-zen, X86_64'. Sorry for my poor English!

**Comment by mjklbhvg** [comment]
I just had a maybe similar problem trying to make an APKBUILD for alpine linux.

Passing --sharedir=/usr/share to ./configure fixed the missing clp.lua error for me.
Otherwise the CLP_PATH is set to /usr/local/share but the .lua files are installed to /usr/share.

Thanks for making clp, its pretty awesome :)

**Comment by jpe90** [comment]
@mjklbhvg That's weird! [`CLP_PATH` should be set to `$SHAREDIR/clp`](https://github.com/jpe90/clp/blob/8749f30343b723f2fafdf9e16fc21e7c5e1457c4/Makefile#L7), and [`$SHAREDIR` should be set to `$PREFIX/share`](https://github.com/jpe90/clp/blob/8749f30343b723f2fafdf9e16fc21e7c5e1457c4/configure#L162), and the [lua files should be copied to `$SHAREDIR/clp`](https://github.com/jpe90/clp/blob/8749f30343b723f2fafdf9e16fc21e7c5e1457c4/Makefile#L39). I'm not sure why the .lua files would end up in `/usr/share` if your `$PREFIX` is set to the default `/usr/local`. 

If possible, it would be helpful if you could post:

- the `make install` output, which looks like:
```
installing executable files to /usr/local/bin
cp -f clp /usr/local/bin && \
	chmod 755 /usr/local/bin/clp;
echo installing support files to /usr/local/share/clp; \
	mkdir -p /usr/local/share/clp; \
	cp -r lua/* /usr/local/share/clp;
installing support files to /usr/local/share/clp
installing manual pages to /usr/local/share/man/man1
sed -e "s/VERSION//" < "man/clp.1" > \
	"/usr/local/share/man/man1/clp.1" && \
	chmod 644 "/usr/local/share/man/man1/clp.1"; \
```
- your generated `config.mk`

@debeetle The above output from your failing AUR installation would help as well. P.S. your English is perfectly understandable, don't worry :)

**Comment by mjklbhvg** [comment]
My mistake was to run ./configure without any arguments.
A make after that would use -DCLP_PATH=\"/usr/local/share/clp\", because /usr/local is the default prefix.
I then used
make DESTDIR="$pkgdir" install PREFIX=/usr
As I undestand it, this installed the support files to /usr/clp, but because of the wrong configure clp expected them in /usr/local
hence the clp.lua not found error.

it seems like the aur package is making the same mistake? (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clp-git)
(the  make install sets the prefix, but the configure doesn't)
But now Im confused how it ever worked in the first place, so I'm probably missing something.

**Comment by jpe90** [comment]
@mjklbhvg good catch! I think it should work if `$PREFIX` is set to `/usr` on configure? Then it should get picked up in the Makefile. I'll do some testing tonight to make sure I understand correctly and then get in touch with the AUR maintainer.

> But now Im confused how it ever worked in the first place

If I had a dollar every time I've said this..

**Comment by debeetle** [comment]
@jpe90 Installation from AUR is actually fine with no error. But if you want, here are the output:
```==> Making package: clp 0.3.0-1 (Wed 08 Mar 2023 11:24:41 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
checking for pkg-config... yes
checking for C compiler... after checking cc
checking whether C compiler works... yes
checking whether compiler accepts -pipe... yes
checking whether compiler accepts -Wall... yes
checking whether compiler accepts -O2... yes
checking whether compiler accepts -ffunction-sections... yes
checking whether compiler accepts -fdata-sections... yes
checking whether linker accepts -Wl,--gc-sections... yes
creating config.mk... done
checking for liblua >= 5.1 ...
 checking for luajit... yes
	checking for lpeg... yes
	checking for luautf8... yes
checking for pcre2...no
completing config.mk... done
cc -c clp.c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -pipe -Wall -O2 -ffunction-sections -fdata-sections -Wall -pedantic -I /home/trunk/.cache/paru/clone/clp/src/clp-v0.3.0/include -I/usr/include/luajit-2.1  -DCLP_PATH=\"/usr/local/share/clp\" -DSRC_LUA_PATH=\"/home/trunk/.cache/paru/clone/clp/src/clp-v0.3.0/lua\" -o clp.o
cc cli.c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -pipe -Wall -O2 -ffunction-sections -fdata-sections -Wall -pedantic -I /home/trunk/.cache/paru/clone/clp/src/clp-v0.3.0/include -I/usr/include/luajit-2.1  -DCLP_PATH=\"/usr/local/share/clp\" -DSRC_LUA_PATH=\"/home/trunk/.cache/paru/clone/clp/src/clp-v0.3.0/lua\" -lluajit-5.1  clp.o -o clp
==> Entering fakeroot environment...
==> Starting package()...
installing executable files to /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/bin
cp -f clp /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/bin && \
chmod 755 /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/bin/clp;
echo installing support files to /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/share/clp; \
mkdir -p /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/share/clp; \
cp -r lua/* /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/share/clp;
installing support files to /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/share/clp
installing manual pages to /home/trunk/.cache/paru/clone/clp/pkg/clp/usr/share/man/man1
sed -e "s/VERSION//" < "man/clp.1" > \
"/home/trunk/.cache/paru/clone/clp/pkg/clp/usr/share/man/man1/clp.1" && \
chmod 644 "/home/trunk/.cache/paru/clone/clp/pkg/clp/usr/share/man/man1/clp.1"; \

==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
usr/bin/clp
==> Creating package "clp"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: clp 0.3.0-1 (Wed 08 Mar 2023 11:24:44 AM CST)
==> Cleaning up...
```

The error information I found is `ERROR: failed to load clp.lua` when I run `clp ~/.xinitrc`. And I run `mv .config/clp/clprc.lua .config/clp/clp.lua` to change the script name. But it turns out `attempt to call a nil value` when I redo the clp command.

Wish these're helpful. Thanks again!

**Comment by jpe90** [comment]
@mjklbhvg 

The difference in $PREFIX between `build()` and `package()` causes the lua files to be packaged under `/usr`:
```
clp-git
├── pkg
│   └── clp-git
│       └── usr
│           ├── bin
│           │   └── clp
│           └── share
│               ├── clp
│               │   ├── ansi_codes.lua
│               │   ├── clp.lua
│               │   ├── ...
```
While the default `/usr/local/` baked into the executable at [build time](https://github.com/jpe90/clp/blob/8749f30343b723f2fafdf9e16fc21e7c5e1457c4/clp.c#L101).

I didn't notice this because I [also baked in the path to the lua files from the source directory](https://github.com/jpe90/clp/blob/8749f30343b723f2fafdf9e16fc21e7c5e1457c4/clp.c#L103) to address #2, which allows you to run clp without installing it. So it was working on my machine because it was just reading the source files. I confirmed this by renaming the AUR folder on my machine, which broke the program.

Passing in `--prefix=/usr` to `./configure` should fix the problem. 

@debeetle 

You actually don't want to change the name of `clprc.lua` to `clp.lua`, because `clprc.lua` is a config file that just specifies the color theme, while the application logic is in `clp.lua`. Both get picked up on the lua path, so renaming the file will cause clp to look for the application logic inside the config file. I think the real issue is that the C code was looking for `clp.lua` in the wrong location.

If you get a chance, could you modify your local PKGBUILD to the following, then re-install and let me know if clp runs correctly? If so I'll let the AUR maintainer know to change it.

```diff
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -21,12 +21,12 @@ pkgver() {

 build() {
        cd "${_pkgname}"
-       ./configure
+        ./configure --prefix=/usr
   make
 }

 package() {
        cd "${_pkgname}"
-       make MANPREFIX=/usr/share/man DESTDIR="${pkgdir}" PREFIX='/usr' install
+        make MANPREFIX=/usr/share/man DESTDIR="${pkgdir}" install
   install -Dm644 "LICENSE" "${pkgdir}/usr/share/licenses/${_pkgname}/LICENSE"
 }
```

**Comment by debeetle** [comment]
@jpe90 That's exactly what the problem is! I find the PKGBUILD in the aur helper build cache folder and follow your suggestion. It works very well. Thanks!

**Comment by jpe90** [comment]
@debeetle Awesome, glad to hear it. I’ll work to get that change upstreamed to the AUR repo so you won’t need to keep that manual modification. Thanks for finding the issue and helping me fix it!

@mjklbhvg Hopefully this fix will work for your alpine package too. Hit me up if you run into other issues and feel free to send a PR adding a link to the install instructions if the package is publicly available.

**Comment by mjklbhvg** [comment]
Yes this works great, thanks for looking into this!
