### ISSUE TITLE
html (and probably embedded) lexing/theming is broken

### ISSUE THREAD

**Issue by Nomarian** [jpe90/clp#9]
No clue if its a problem with the themes or that the extra styles are not handled correctly or what.

The legacy lexers did work better than the new ones.

![image](https://user-images.githubusercontent.com/50381/180527343-a33f45cd-7464-4150-a60a-93061ccec1c2.png)

This is from the readme.html from the luadocs

I have no clue what causes this or how to fix it.

**Comment by jpe90** [comment]
I think it's a theming/styling issue and not the lexers, since it html renders correctly in textadept.

Here's it rendering a script tag:

![Screen Shot 2022-07-23 at 3 17 23 AM](https://user-images.githubusercontent.com/9307830/180595020-2508f8db-b57f-4c0e-acaf-ab7b5c6731d7.png)

Then rendering again after adding a color for an attribute:

```
diff --git a/lua/theme.lua b/lua/theme.lua
index c110e4f..7cb54b5 100644
--- a/lua/theme.lua
+++ b/lua/theme.lua
@@ -7,6 +7,7 @@ local default_theme = {
        -- italics => underscore
        ['default'] =  colors.white,
        ['nothing'] = '',
+       ['attribute'] = colors.yellow .. colors.bright,
        ['class'] = colors.yellow .. colors.bright,
        ['comment'] = colors.blue .. colors.bright,
        ['constant'] = colors.cyan .. colors.bright,
```
![Screen Shot 2022-07-23 at 3 20 27 AM](https://user-images.githubusercontent.com/9307830/180595061-f2dec1cc-a510-4a03-afb9-638b44e9badb.png)

**Comment by jpe90** [comment]
I'm using the following to look at what the lexer is picking up:
```
diff --git a/lua/clp.lua b/lua/clp.lua
index 4264dc1..477228e 100644
--- a/lua/clp.lua
+++ b/lua/clp.lua
@@ -105,11 +105,16 @@ function write_text(text, lexer, style)
                        -- a series in order to properly display multibyte
                        -- UTF-8 characters.
                        if not (last == 'default' and name == 'default') then
-                               io.write(tostring(current_style))
+                               -- io.write(tostring(current_style))
                        end
                        last = name
                end
+               -- io.write(text:sub(token_start, token_end))
+               io.write('TOKEN ')
+               io.write(name)
+               io.write(' TEXT ')
                io.write(text:sub(token_start, token_end))
+               io.write('\n')
                token_start = token_end + 1
        end
 end
```

Running on the html line above yields:

```
TOKEN single_element TEXT <link
TOKEN html_whitespace TEXT
TOKEN attribute TEXT rel
TOKEN default TEXT =
TOKEN string TEXT "stylesheet"
TOKEN html_whitespace TEXT
TOKEN attribute TEXT href
TOKEN default TEXT =
TOKEN string TEXT "/css/style.css"
TOKEN element TEXT >
```

**Comment by jpe90** [comment]
It looks like the new lexers let you add styles via rules. For example HTML lexer includes a rule to style attributes as types:

https://github.com/orbitalquark/scintillua/blob/020ce95c1389f6ba5fb7ad6cc0c14fadcbcff086/lexers/html.lua#L69

This gets picked up by textadept by the following:

https://github.com/orbitalquark/textadept/blob/e1d0eb4dca0ca2f6e37f0af5eae2188042069ecc/themes/light.lua#L82

IIUC clp is currently coloring by looking up the token type directly in a table it defines and ignores styles/rules completely:

https://github.com/jpe90/clp/blob/559f62e52987f25532e6ede02c30591eae4db0f3/lua/theme.lua#L5-L29

So I guess either additional tokens need to be defined in that table or it should be coloring based on styles rather than tokens.  I'm not sure how to make the latter work.

I'll do more digging/thinking, in the meantime suggestions/PRs are welcome.

**Comment by jpe90** [comment]
WIP fix at a362770f4529bad4e338468e28893bae1bf972ce, html seems to works there at least
<img width="1141" alt="Screen Shot 2022-07-24 at 8 44 53 AM" src="https://user-images.githubusercontent.com/9307830/180647629-84010f72-3da2-4589-ac37-63c8098bdc29.png">

**Comment by Nomarian** [comment]
No clue what you did but it works.

**Comment by jpe90** [comment]
It seems to at least! Embedded lexers seem to work as well after 753d51f0fca4a06b714d6161f59ee9c548ee7125, merged to master.
